### ISSUE TITLE
MVP element comments list

### ISSUE THREAD

**Issue by CSchmitz81** [F4IF/ctree-demo#101]
For the MVP implementation of feedback we only support comments, which each have a text description and their own rating score.

For this ticket, comments should be listed vertically under the comment entry in the element details dialog.  This should use hardcoded placeholder data unless #100 is already implemented.  This should also support a loading spinner at the end of the list and triggering a `loading` flag until a flag for `loadingComplete` has been set.  This loading behavior should be similar to how the suggested elements list behaves on the main page.

**Comment by CSchmitz81** [comment]
Unassigning from @mrapogee due to lack of feedback and no

**Comment by CSchmitz81** [comment]
Someone was working on this 5/7 and needs to mark it as assigned to themselves.

**Comment by CSchmitz81** [comment]
@dhallmanlearning & @flagnark, how's the progress on this going?  Is there a branch with changes related to it?

**Comment by dhallmanlearning** [comment]
Sorry Chris, I have been focusing on learning data science and have not been working on this. I have removed myself as an assignee

**Comment by CSchmitz81** [comment]
Removed assignee due to lack of progress and communication

**Comment by CSchmitz81** [comment]
Changes merged
