### ISSUE TITLE
Fix New Firebase Access

### ISSUE THREAD

**Issue by CSchmitz81** [F4IF/ctree-demo#115]
Changes to Firebase creation appear to have broken our Firebase setup instructions.  When a new Firebase Realtime Database is created and the config values are set in the project the data isn't read correctly from the Database.  Existing Firebase Realtime Database instances continue to work correctly, indicating there's something different about new Realtime Database instances created.

It may be easier to debug this by creating a separate project which just gets data from a Firebase Realtime Database using the same [polymerfire](https://www.webcomponents.org/element/FirebaseExtended/polymerfire) web component we use.  It's unclear if there's an updated version of polymerfire which would work better than the version we use (2.2.1) in the [MVP branch](https://github.com/F4IF/ctree-demo/tree/mvp).

Once a fix has been found, a PR for the MVP branch should be created with any changes needed to fix the issue.  If needed, the Firebase instructions on the Wiki should also be updated.

**Comment by enosvazquez** [comment]
My mistake - I accidentally clicked on the close button.

**Comment by tabatahg** [comment]
Managed to make it work once. Recreated error again to double check. Could not fix second time.

The error may possibly stem from authentication. I've noticed that the Api key is passed when it works.

When the error persists, the Apikey is not passed.

**Comment by CSchmitz81** [comment]
Upon further testing at this month's hackathon we haven't been able to reproduce the issue.  If this pops up again we'll reopen it.
