### ISSUE TITLE
Landing Page Footer Update

### ISSUE THREAD

**Issue by CSchmitz81** [F4IF/ctree-demo#120]
The landing page footer needs to be updated to match the new comps.  This should adjust automatically to the mobile style based on the width of the screen.

Please base your changes on the [develop-landing-page](https://github.com/F4IF/ctree-demo/tree/develop-landing-page) branch.

See the comps for [desktop](https://projects.invisionapp.com/share/76SWF7LCQXT#/screens/373007242_Landing_Page) and [mobile](https://projects.invisionapp.com/share/5KT3GCRVJB2#/screens/375108141_Ctree_Mobile) for reference.

**Comment by P1X3L0V4** [comment]
I'd be happy to help with this one. Can you please assign me?

**Comment by CSchmitz81** [comment]
Closing now that the changes have been merged.
